import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const COURSES_DATA = [
  {
    id: 'course-1',
    slug: 'full-stack-web-development',
    title: 'Full Stack Web Development',
    subtitle: 'Architect, build, and deploy scalable production web systems with TypeScript, Next.js, Node.js, and PostgreSQL.',
    shortDescription: 'Master end-to-end engineering from modern React component architecture to distributed backend APIs and cloud deployment.',
    fullDescription: 'Designed for aspiring software engineers and frontend developers transitioning to full-stack architecture. This programme guides you through building production-grade applications using modern TypeScript, React Server Components, relational database design, automated testing, and CI/CD pipelines. Every module concludes with a code-reviewed systems project.',
    category: 'Development',
    level: 'Intermediate',
    duration: '16 Weeks',
    totalHours: 94,
    projectsCount: 6,
    rating: 4.9,
    reviewsCount: 1420,
    studentsCount: 14850,
    price: 249,
    originalPrice: 399,
    discountPercent: 38,
    imageUrl: '/images/course_fullstack_dev_1791367137460.jpg',
    visualAccent: 'blue',
    instructor: {
      name: 'Marcus Vance',
      role: 'Principal Systems Architect',
      companyContext: 'Enterprise Cloud Infrastructure Lab',
      initials: 'MV',
      experienceYears: 12,
      studentsTaught: '18,400+',
      bio: 'Marcus has led distributed web engineering teams for over a decade, specializing in high-throughput TypeScript services, edge computing, and resilient frontend architectures.',
    },
    whatYouWillLearn: [
      'Architect modular React & Next.js applications with server and client component boundaries',
      'Design normalized relational database schemas with PostgreSQL, Prisma ORM, and connection pooling',
      'Implement multi-tenant authentication, RBAC authorization, and encrypted session handling',
      'Build performant REST & GraphQL APIs with automated validation, caching, and rate limiting',
      'Deploy containerized workloads to Docker, Kubernetes, and edge-native serverless infrastructure',
      'Configure automated CI/CD pipelines with GitHub Actions, linting, and end-to-end Playwright tests',
    ],
    prerequisites: [
      'Solid grasp of JavaScript fundamentals (ES6+, promises, async/await, array methods)',
      'Basic familiarity with React concepts (components, props, state, hooks)',
      'Working knowledge of Git version control (branching, commits, pull requests)',
    ],
    curriculum: [
      {
        id: 'mod-1',
        number: '01',
        title: 'Advanced TypeScript & Runtime Safety',
        summary: 'Deep-dive into generics, utility types, discriminated unions, and schema validation with Zod.',
        duration: '14 Hours',
        lessons: [
          { id: 'les-1-1', title: 'Generics, Conditional Types, and Type Narrowing', duration: '45m', type: 'video', isPreview: true },
          { id: 'les-1-2', title: 'Discriminated Unions & Exhaustive Type Checking', duration: '50m', type: 'video', isPreview: false },
          { id: 'les-1-3', title: 'Runtime Schema Validation with Zod & Type Inversion', duration: '60m', type: 'video', isPreview: true },
          { id: 'les-1-4', title: 'Project: Type-Safe Configuration Engine', duration: '3h', type: 'project', isPreview: false },
        ],
      },
      {
        id: 'mod-2',
        number: '02',
        title: 'Full-Stack Next.js Architecture',
        summary: 'Master Next.js App Router, Server Components, Streaming SSR, and Server Actions.',
        duration: '18 Hours',
        lessons: [
          { id: 'les-2-1', title: 'Server vs. Client Components: Mental Model & Boundaries', duration: '55m', type: 'video', isPreview: true },
          { id: 'les-2-2', title: 'Streaming with Suspense & Optimistic UI Updates', duration: '60m', type: 'video', isPreview: false },
          { id: 'les-2-3', title: 'Server Actions with Validation and Error Boundaries', duration: '65m', type: 'video', isPreview: false },
          { id: 'les-2-4', title: 'Project: Real-Time Collaborative Workspace', duration: '4h', type: 'project', isPreview: false },
        ],
      },
    ],
    reviews: [
      {
        id: 'rev-1',
        studentName: 'Julian Mercer',
        studentInitials: 'JM',
        role: 'Senior Frontend Engineer at DataFlow',
        rating: 5,
        date: 'September 2026',
        comment: 'The architectural rigor in this course is unmatched. Module 3 alone saved us weeks of database restructuring at work.',
        outcomeMetric: 'Promoted to Senior Full Stack Engineer within 4 months',
      },
    ],
    faqs: [
      {
        question: 'How much time commitment is required per week?',
        answer: 'We recommend 6 to 8 hours per week, covering 2 to 3 hours of lectures and 4 to 5 hours of hands-on project implementation.',
      },
      {
        question: 'Will I receive a verified certificate upon completion?',
        answer: 'Yes. Upon successfully submitting and passing all 6 capstone project code reviews, you will receive a cryptographically verifiable certificate.',
      },
    ],
    featured: true,
  },
  {
    id: 'course-2',
    slug: 'ui-ux-design',
    title: 'UI/UX Design & Design Systems',
    subtitle: 'From user psychology and wireframing to multi-brand design tokens, Figma variables, and production handoff.',
    shortDescription: 'Master modern product design: user research, iterative prototyping, accessibility audits, and scalable token systems.',
    fullDescription: 'Craft intuitive, accessible digital experiences that scale. This course takes you through end-to-end product design cycles, starting with deep generative user research, synthesis, and wireframing, progressing to high-fidelity Figma components with auto-layout and interactive variants.',
    category: 'Design',
    level: 'Beginner',
    duration: '12 Weeks',
    totalHours: 72,
    projectsCount: 5,
    rating: 4.8,
    reviewsCount: 980,
    studentsCount: 11200,
    price: 199,
    originalPrice: 320,
    discountPercent: 38,
    imageUrl: '/images/course_uiux_design_1791367148988.jpg',
    visualAccent: 'indigo',
    instructor: {
      name: 'Clara Lindqvist',
      role: 'Staff Product Designer & Design Systems Lead',
      companyContext: 'Previously Head of Product Design at Finora & Spotify Consultant',
      bio: 'Clara has spent 10 years crafting accessible product interfaces, enterprise design system tokens, and UX design curriculums.',
      initials: 'CL',
      experienceYears: 10,
      studentsTaught: '12,500+',
    },
    whatYouWillLearn: [
      'Conduct generative user research, persona creation, empathy mapping, and user journey flows',
      'Build comprehensive design systems with Figma variables, component properties, and semantic tokens',
      'Apply WCAG 2.2 AA accessibility standards for color contrast, touch targets, and keyboard navigation',
      'Design complex multi-device responsive interfaces with modern Auto Layout and interactive variants',
    ],
    prerequisites: [
      'Basic familiarity with digital software tools (Figma, Sketch, or Adobe XD is a plus, but not required)',
      'Curiosity for user psychology, digital ergonomics, and visual hierarchy',
    ],
    curriculum: [
      {
        id: 'mod-1',
        number: '01',
        title: 'Design Thinking & User Research',
        summary: 'Qualitative research methods, heuristic evaluation, persona formulation, and user flows.',
        duration: '12 Hours',
        lessons: [
          { id: 'les-1-1', title: 'User Interview Techniques and Insight Synthesis', duration: '50m', type: 'video', isPreview: true },
          { id: 'les-1-2', title: 'Creating High-Utility Personas and Empathy Maps', duration: '45m', type: 'video', isPreview: false },
        ],
      },
    ],
    reviews: [
      {
        id: 'rev-1',
        studentName: 'Maya Thorne',
        studentInitials: 'MT',
        role: 'Product Designer at FinVenture',
        rating: 5,
        date: 'August 2026',
        comment: 'This course turned my scattered portfolio into 3 enterprise-grade case studies. The Figma token modules were exceptional.',
        outcomeMetric: 'Landed first Product Designer role within 60 days',
      },
    ],
    faqs: [
      {
        question: 'Do I need prior graphic design experience?',
        answer: 'No prior graphic design background is required. We start from foundational visual hierarchy, typography, and spacing principles.',
      },
    ],
    featured: true,
  },
  {
    id: 'course-3',
    slug: 'ai-and-machine-learning',
    title: 'AI & Machine Learning Engineering',
    subtitle: 'Build, evaluate, and deploy applied machine learning models, LLM pipelines, and retrieval-augmented systems in Python.',
    shortDescription: 'Bridge statistical learning theory and production MLOps with hands-on PyTorch, vector search, and model evaluation labs.',
    fullDescription: 'Move beyond high-level API wrappers to understand the mathematics, training pipelines, and deployment architectures behind modern AI systems. You will implement classical supervised models, train deep neural networks in PyTorch, engineer deterministic evaluation harnesses for large language models, and deploy low-latency inference services.',
    category: 'Data & AI',
    level: 'Advanced',
    duration: '18 Weeks',
    totalHours: 108,
    projectsCount: 6,
    rating: 4.9,
    reviewsCount: 845,
    studentsCount: 9420,
    price: 279,
    originalPrice: 449,
    discountPercent: 38,
    imageUrl: '/images/course_data_ai_1791367159844.jpg',
    visualAccent: 'violet',
    instructor: {
      name: 'Dr. Aris Thorne',
      role: 'Lead Applied ML Scientist',
      companyContext: 'Autonomous Systems Research Group',
      bio: 'Dr. Thorne holds a PhD in Computational Statistics and has architected production recommendation and NLP pipelines serving millions of daily predictions.',
      initials: 'AT',
      experienceYears: 11,
      studentsTaught: '9,800+',
    },
    whatYouWillLearn: [
      'Implement supervised and unsupervised learning pipelines with Scikit-Learn and XGBoost',
      'Build and train custom neural network architectures using PyTorch and GPU acceleration',
      'Design production RAG architectures with hybrid vector search and reranking pipelines',
      'Construct automated evaluation benchmarks to measure precision, recall, and latency',
      'Fine-tune open-weights transformer models using LoRA and quantized parameter adapters',
      'Deploy containerized inference APIs with model monitoring and drift detection',
    ],
    prerequisites: [
      'Working proficiency in Python programming and data structures',
      'Foundational familiarity with linear algebra, calculus, and probability',
    ],
    curriculum: [
      {
        id: 'ai-mod-1',
        number: 'Module 01',
        title: 'Introduction & Statistical Learning Foundations',
        summary: 'Master feature engineering, cross-validation, bias-variance tradeoffs, and gradient boosting.',
        duration: '3 Weeks · 18 Hours',
        lessons: [
          { id: 'ai-101', title: 'Mathematical Foundations: Linear Algebra & Optimization', duration: '55m', type: 'video', isPreview: true },
          { id: 'ai-102', title: 'Feature Engineering & Gradient Boosted Decision Trees', duration: '62m', type: 'video', isPreview: true },
          { id: 'ai-103', title: 'Lab: Credit Risk & Churn Prediction Pipeline', duration: '3h 00m', type: 'lab' },
        ],
      },
    ],
    reviews: [
      {
        id: 'ai-rev-1',
        studentName: 'Karthik Subramanian',
        studentInitials: 'KS',
        role: 'ML Engineer at Enterprise Analytics Firm',
        rating: 5,
        date: 'September 2026',
        comment: 'Building the transformer attention block from scratch in Module 02 and writing rigorous retrieval evaluation harnesses in Module 03 gave me massive confidence in technical interviews.',
        outcomeMetric: 'Promoted from Backend Developer to Applied ML Engineer',
      },
    ],
    faqs: [
      {
        question: 'Do I need an expensive local GPU to complete the labs?',
        answer: 'No. All deep learning and fine-tuning labs are configured to run seamlessly on cloud GPU notebooks with step-by-step environment scripts.',
      },
    ],
    featured: true,
  },
  {
    id: 'course-4',
    slug: 'data-analytics',
    title: 'Data Analytics & Business Intelligence',
    subtitle: 'Transform raw operational data into executive decisions using advanced SQL, Python, statistical modeling, and BI dashboards.',
    shortDescription: 'Master analytical SQL window functions, Python exploratory analysis, cohort retention modeling, and executive storytelling.',
    fullDescription: 'Designed for analysts, operations professionals, and career switchers seeking quantitative fluency. You will work with multi-million-row datasets to write complex SQL queries, automate data cleaning pipelines in Python with Pandas and Polars, design statistically sound A/B experiments, and build interactive decision dashboards.',
    category: 'Data & AI',
    level: 'Beginner',
    duration: '14 Weeks',
    totalHours: 80,
    projectsCount: 5,
    rating: 4.8,
    reviewsCount: 1150,
    studentsCount: 13100,
    price: 219,
    originalPrice: 349,
    discountPercent: 37,
    imageUrl: '/images/course_data_ai_1791367159844.jpg',
    visualAccent: 'cyan',
    instructor: {
      name: 'Nadia Okafor',
      role: 'Director of Product Analytics',
      companyContext: 'Global Commerce Analytics Division',
      initials: 'NO',
      experienceYears: 9,
      studentsTaught: '14,200+',
      bio: 'Nadia has built analytics organizations from the ground up, specializing in revenue attribution, experimentation frameworks, and executive data storytelling.',
    },
    whatYouWillLearn: [
      'Write complex SQL queries using CTEs, window functions, and query execution plans',
      'Clean, transform, and aggregate large datasets in Python using Pandas and Polars',
      'Design and analyze A/B tests with hypothesis testing, p-values, and statistical power',
      'Build cohort retention matrices, funnel conversion models, and LTV forecasts',
    ],
    prerequisites: [
      'Comfort with basic high-school mathematics and spreadsheet formulas',
      'No prior SQL or Python coding experience required',
    ],
    curriculum: [
      {
        id: 'da-mod-1',
        number: 'Module 01',
        title: 'Introduction & Analytical SQL Mastery',
        summary: 'Query relational data warehouses using joins, aggregations, CTEs, and window functions.',
        duration: '3 Weeks · 18 Hours',
        lessons: [
          { id: 'da-101', title: 'Relational Schemas, Joins & Filtering at Scale', duration: '45m', type: 'video', isPreview: true },
          { id: 'da-102', title: 'Window Functions: LEAD, LAG, RANK & Rolling Averages', duration: '58m', type: 'video', isPreview: true },
          { id: 'da-103', title: 'Project: E-Commerce Supply Chain & Cohort SQL Audit', duration: '3h 30m', type: 'project' },
        ],
      },
    ],
    reviews: [
      {
        id: 'da-rev-1',
        studentName: 'Liam Gallagher',
        studentInitials: 'LG',
        role: 'Business Intelligence Analyst',
        rating: 5,
        date: 'August 2026',
        comment: 'The SQL window functions module and experimentation framework helped me pass three technical SQL screens with ease.',
        outcomeMetric: 'Moved from Operations Coordinator to BI Analyst',
      },
    ],
    faqs: [
      {
        question: 'Will I learn both SQL and Python?',
        answer: 'Yes. Roughly 40% of the technical curriculum focuses on advanced analytical SQL, 40% on Python data manipulation and statistics, and 20% on BI modeling.',
      },
    ],
    featured: true,
  },
  {
    id: 'course-5',
    slug: 'digital-marketing',
    title: 'Digital Marketing & Growth Systems',
    subtitle: 'Build measurable acquisition engines across technical SEO, paid performance media, conversion rate optimization, and lifecycle attribution.',
    shortDescription: 'Replace guesswork with data-driven growth loops, technical search architecture, and full-funnel revenue attribution.',
    fullDescription: 'Modern marketing is a quantitative discipline. This programme teaches you how to engineer repeatable customer acquisition systems, structure high-intent search and paid media campaigns, run systematic landing page conversion experiments, and measure true incrementality and customer acquisition cost (CAC) payback.',
    category: 'Marketing',
    level: 'Intermediate',
    duration: '10 Weeks',
    totalHours: 60,
    projectsCount: 4,
    rating: 4.8,
    reviewsCount: 730,
    studentsCount: 8640,
    price: 179,
    originalPrice: 299,
    discountPercent: 40,
    imageUrl: '/images/course_uiux_design_1791367148988.jpg',
    visualAccent: 'emerald',
    instructor: {
      name: 'Julian Mercer',
      role: 'VP of Growth & Acquisition',
      companyContext: 'ScaleUp Revenue Advisory',
      initials: 'JM',
      experienceYears: 10,
      studentsTaught: '8,900+',
      bio: 'Julian has managed over $40M in performance media spend and built organic search engines for B2B SaaS and consumer subscription brands.',
    },
    whatYouWillLearn: [
      'Architect programmatic and technical SEO strategies rooted in search intent',
      'Structure paid acquisition campaigns with disciplined CAC and ROAS guardrails',
      'Design high-converting landing pages with clear proposition-to-proof hierarchy',
    ],
    prerequisites: [
      'Basic familiarity with digital channels or commercial operations',
    ],
    curriculum: [
      {
        id: 'dm-mod-1',
        number: 'Module 01',
        title: 'Introduction & Quantitative Growth Modeling',
        summary: 'Understand unit economics, LTV:CAC ratios, payback periods, and funnel diagnostics.',
        duration: '2 Weeks · 12 Hours',
        lessons: [
          { id: 'dm-101', title: 'Unit Economics: CAC, LTV, Churn & Payback Math', duration: '44m', type: 'video', isPreview: true },
        ],
      },
    ],
    reviews: [
      {
        id: 'dm-rev-1',
        studentName: 'Hannah Abbott',
        studentInitials: 'HA',
        role: 'Growth Marketing Manager',
        rating: 5,
        date: 'September 2026',
        comment: 'Finally a marketing course that focuses on unit economics, attribution, and technical execution instead of surface-level social media tips.',
        outcomeMetric: 'Reduced paid acquisition CAC by 28% at current company',
      },
    ],
    faqs: [
      {
        question: 'Does this cover both B2B and B2C marketing?',
        answer: 'Yes. The frameworks cover high-velocity consumer subscription loops as well as longer-cycle B2B pipeline generation.',
      },
    ],
    featured: true,
  },
  {
    id: 'course-6',
    slug: 'business-and-leadership',
    title: 'Business Strategy & Product Leadership',
    subtitle: 'Lead cross-functional teams, align product roadmaps with P&L outcomes, and execute strategic decisions under uncertainty.',
    shortDescription: 'Equip yourself with executive frameworks for product strategy, financial literacy, stakeholder alignment, and operational execution.',
    fullDescription: 'Built for emerging engineering managers, senior product managers, and operational leaders. You will master P&L financial modeling, competitive moat analysis, OKR execution without bureaucratic overhead, and high-stakes communication with boards and cross-functional teams.',
    category: 'Business',
    level: 'Advanced',
    duration: '10 Weeks',
    totalHours: 56,
    projectsCount: 4,
    rating: 4.9,
    reviewsCount: 620,
    studentsCount: 7350,
    price: 229,
    originalPrice: 369,
    discountPercent: 38,
    imageUrl: '/images/course_fullstack_dev_1791367137460.jpg',
    visualAccent: 'amber',
    instructor: {
      name: 'Victoria Sterling',
      role: 'Chief Operating Officer & Executive Advisor',
      companyContext: 'Enterprise Technology Group',
      initials: 'VS',
      experienceYears: 15,
      studentsTaught: '7,500+',
      bio: 'Victoria has scaled product and operational teams from 30 to 600+ employees across three high-growth technology enterprises.',
    },
    whatYouWillLearn: [
      'Read and model SaaS P&L statements, gross margins, and capital allocation',
      'Formulate defensible product strategy and competitive positioning',
      'Run high-accountability quarterly planning and outcome-driven roadmaps',
    ],
    prerequisites: [
      '2+ years of professional experience in technology, product, design, or operations recommended',
    ],
    curriculum: [
      {
        id: 'bl-mod-1',
        number: 'Module 01',
        title: 'Introduction & Strategic Market Diagnosis',
        summary: 'Evaluate market structure, switching costs, network effects, and strategic leverage.',
        duration: '2 Weeks · 11 Hours',
        lessons: [
          { id: 'bl-101', title: 'Diagnosing Competitive Moats & Value Capture', duration: '46m', type: 'video', isPreview: true },
        ],
      },
    ],
    reviews: [
      {
        id: 'bl-rev-1',
        studentName: 'Mateo Silva',
        studentInitials: 'MS',
        role: 'Senior Engineering Manager',
        rating: 5,
        date: 'September 2026',
        comment: 'Module 02 on financial literacy gave me the exact vocabulary I needed to advocate for platform architecture investments with our CFO and VP of Product.',
        outcomeMetric: 'Stepped up to Director of Engineering leading 4 squads',
      },
    ],
    faqs: [
      {
        question: 'Is this meant for technical or non-technical leaders?',
        answer: 'Both. Engineering leads gain commercial and financial fluency, while business and product leads master technical team topology and execution systems.',
      },
    ],
    featured: true,
  },
];

const BLOGS_DATA = [
  {
    id: 'blog-1',
    slug: 'bridging-the-senior-engineering-gap-in-2026',
    title: 'Bridging the Architecture Gap: How Mid-Level Engineers Step Into System Ownership',
    excerpt: 'Why syntax fluency is no longer the primary bottleneck in technical interviews—and how mastering relational data modeling, observability, and trade-off documentation accelerates career progression.',
    category: 'Career',
    publishedAt: 'October 4, 2026',
    readingTime: '7 min read',
    featured: true,
    imageUrl: '/images/blog_featured_editorial_1791367171346.jpg',
    visualTheme: 'navy',
    author: {
      name: 'Marcus Vance',
      role: 'Principal Systems Architect & Lead Instructor',
      initials: 'MV',
      bio: 'Marcus has interviewed over 400 software engineers and leads the Full Stack Web Development curriculum at Appic Skill.',
    },
    sections: [
      {
        id: 'sec-1',
        heading: 'The Shift From Code Production to Decision Quality',
        paragraphs: [
          'In modern engineering teams, code generation is increasingly commoditized by intelligent developer tooling. What remaining engineering leaders value most is decision quality: knowing which database index to create, understanding cache invalidation race conditions, and drafting structured Architectural Decision Records (ADRs).',
          'When stepping into senior engineering, your value is measured not by lines of code merged, but by the downstream failure modes you prevent before writing a single line.',
        ],
        keyTakeaway: 'Senior engineers distinguish themselves by anticipating system bottlenecks and writing clear trade-off documents.',
      },
    ],
  },
];

const WORKSHOPS_DATA = [
  {
    id: 'ws-1',
    title: 'Architecting Low-Latency RAG Pipelines with Hybrid Search',
    topic: 'Hands-on session covering chunking heuristics, dense + sparse retrieval, and automated precision scoring.',
    category: 'Data & AI',
    date: 'Oct 18, 2026',
    time: '10:00 AM EST',
    duration: '120 Mins · Live Lab',
    instructorName: 'Dr. Aris Thorne',
    instructorRole: 'Lead Applied ML Scientist',
    instructorInitials: 'AT',
    seatsTotal: 150,
    seatsRemaining: 19,
    keyTakeaways: [
      'Implement Reciprocal Rank Fusion in Python',
      'Benchmark retrieval recall on technical documents',
      'Live Q&A on production inference costs',
    ],
  },
  {
    id: 'ws-2',
    title: 'Multi-Brand Design Tokens & Dark Mode Architecture in Figma',
    topic: 'Build a semantic variable architecture that scales across web and mobile with clean CSS custom property handoff.',
    category: 'Design',
    date: 'Oct 22, 2026',
    time: '1:00 PM EST',
    duration: '90 Mins · Interactive Critique',
    instructorName: 'Clara Lindqvist',
    instructorRole: 'Staff Product Designer',
    instructorInitials: 'CL',
    seatsTotal: 120,
    seatsRemaining: 14,
    keyTakeaways: [
      'Structure primitive vs. semantic token tiers',
      'Prevent dark-mode contrast failures systematically',
      'Live portfolio and component clinic',
    ],
  },
  {
    id: 'ws-3',
    title: 'React 19 Server Actions, Optimistic UI & Database Transactions',
    topic: 'Live coding session building a resilient booking workflow with zero layout shift and strict type safety.',
    category: 'Development',
    date: 'Oct 27, 2026',
    time: '11:30 AM EST',
    duration: '120 Mins · Live Coding',
    instructorName: 'Marcus Vance',
    instructorRole: 'Principal Systems Architect',
    instructorInitials: 'MV',
    seatsTotal: 200,
    seatsRemaining: 28,
    keyTakeaways: [
      'Handle race conditions in optimistic UI updates',
      'Structure PostgreSQL row-level locking',
      'Architecture review with live attendees',
    ],
  },
];

async function main() {
  console.log('🌱 Seeding all 6 courses into Supabase PostgreSQL...');

  // Seed all 6 Courses
  for (const course of COURSES_DATA) {
    await prisma.course.upsert({
      where: { slug: course.slug },
      update: {
        title: course.title,
        subtitle: course.subtitle,
        shortDescription: course.shortDescription,
        fullDescription: course.fullDescription,
        category: course.category,
        level: course.level,
        duration: course.duration,
        totalHours: course.totalHours,
        projectsCount: course.projectsCount,
        rating: course.rating,
        reviewsCount: course.reviewsCount,
        studentsCount: course.studentsCount,
        price: course.price,
        originalPrice: course.originalPrice,
        discountPercent: course.discountPercent,
        imageUrl: course.imageUrl,
        visualAccent: course.visualAccent,
        instructor: course.instructor,
        whatYouWillLearn: course.whatYouWillLearn,
        prerequisites: course.prerequisites,
        curriculum: course.curriculum,
        reviews: course.reviews,
        faqs: course.faqs,
        featured: course.featured,
      },
      create: {
        id: course.id,
        slug: course.slug,
        title: course.title,
        subtitle: course.subtitle,
        shortDescription: course.shortDescription,
        fullDescription: course.fullDescription,
        category: course.category,
        level: course.level,
        duration: course.duration,
        totalHours: course.totalHours,
        projectsCount: course.projectsCount,
        rating: course.rating,
        reviewsCount: course.reviewsCount,
        studentsCount: course.studentsCount,
        price: course.price,
        originalPrice: course.originalPrice,
        discountPercent: course.discountPercent,
        imageUrl: course.imageUrl,
        visualAccent: course.visualAccent,
        instructor: course.instructor,
        whatYouWillLearn: course.whatYouWillLearn,
        prerequisites: course.prerequisites,
        curriculum: course.curriculum,
        reviews: course.reviews,
        faqs: course.faqs,
        featured: course.featured,
      },
    });
  }

  // Seed Blogs
  for (const article of BLOGS_DATA) {
    await prisma.blogArticle.upsert({
      where: { slug: article.slug },
      update: {
        title: article.title,
        excerpt: article.excerpt,
        category: article.category,
        publishedAt: article.publishedAt,
        readingTime: article.readingTime,
        featured: article.featured,
        imageUrl: article.imageUrl,
        visualTheme: article.visualTheme,
        author: article.author,
        sections: article.sections,
      },
      create: {
        id: article.id,
        slug: article.slug,
        title: article.title,
        excerpt: article.excerpt,
        category: article.category,
        publishedAt: article.publishedAt,
        readingTime: article.readingTime,
        featured: article.featured,
        imageUrl: article.imageUrl,
        visualTheme: article.visualTheme,
        author: article.author,
        sections: article.sections,
      },
    });
  }

  // Seed Workshops
  for (const workshop of WORKSHOPS_DATA) {
    await prisma.workshop.upsert({
      where: { id: workshop.id },
      update: {
        title: workshop.title,
        topic: workshop.topic,
        category: workshop.category,
        date: workshop.date,
        time: workshop.time,
        duration: workshop.duration,
        instructorName: workshop.instructorName,
        instructorRole: workshop.instructorRole,
        instructorInitials: workshop.instructorInitials,
        seatsTotal: workshop.seatsTotal,
        seatsRemaining: workshop.seatsRemaining,
        keyTakeaways: workshop.keyTakeaways,
      },
      create: {
        id: workshop.id,
        title: workshop.title,
        topic: workshop.topic,
        category: workshop.category,
        date: workshop.date,
        time: workshop.time,
        duration: workshop.duration,
        instructorName: workshop.instructorName,
        instructorRole: workshop.instructorRole,
        instructorInitials: workshop.instructorInitials,
        seatsTotal: workshop.seatsTotal,
        seatsRemaining: workshop.seatsRemaining,
        keyTakeaways: workshop.keyTakeaways,
      },
    });
  }

  console.log('✅ All 6 courses seeded successfully into Supabase!');
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
